---
user: trough
venv_root: /opt
local_data: /var/tmp/trough
read_port: 6444
write_port: 6222
sync_port: 6111
minimum_assignments: "lambda segment_id: 2 if segment_id.isnumeric() and int(segment_id) > 200000 else 1"
hdfs_host: null
hdfs_port: 8000
sync_loop_timing: 120

udp_log_host: UDP_LOG_HOST_UNSET
sync_local_udp_log_port: 6913
sync_server_udp_log_port: 6912
write_provisioner_local_udp_log_port: 6911
write_provisioner_server_udp_log_port: 6910
write_udp_log_port: 6922
read_udp_log_port: 6944